In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'cgpa' : [8,7,6,5],
    'profile score' :[8,9,10,12],
    'lpa' : [4,5,6,7]
}
df = pd.DataFrame(data)
df

cgpa  profile score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [5]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [7]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [8]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.get_weights()

[array([[0.7908038 , 0.66290224],
        [1.1170033 , 0.55705595]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.0337809 ],
        [0.10436904]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
new_weights = [np.array([[0.1,0.1],
                          [0.1,0.1]], dtype = np.float32),
               np.array([0.,0.], dtype = np.float32),
               np.array([[0.1],
                         [0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)
               ]

In [12]:
model.set_weights(new_weights)

In [13]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
optimize = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimize)

In [15]:
model.fit(df.iloc[:,:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 31.1240 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.8654 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.8248 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.0582 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 21.5213 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 29.3414 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22.4695
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20.5347 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 28.9120 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.9303 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.1553 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 18.3501 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.4829
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 20.3282 
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 18.6551 
Epoch 16/75
4/4 ━━

In [16]:
model.get_weights()

[array([[0.3737915, 0.3737915],
        [0.3656774, 0.3656774]], dtype=float32),
 array([0.27245364, 0.27245364], dtype=float32),
 array([[0.37305042],
        [0.37305042]], dtype=float32),
 array([0.20485309], dtype=float32)]